# Generated by Django 5.2.4 on 2025-07-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='naem',
            new_name='name',
        ),
    ]
