# Generated by Django 5.2.4 on 2025-07-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_naem_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
