# Generated by Django 5.2.1 on 2025-06-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.product')),
                ('nameofcompany', models.CharField(max_length=100)),
                ('nameofproduct', models.CharField(max_length=100)),
                ('productprice', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
            bases=('myapp.product',),
        ),
    ]
