# Generated by Django 5.2.1 on 2025-06-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_electricproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricproduct',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='electricproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
