# Generated by Django 5.2.1 on 2025-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_electricproduct_product_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ElectricProduct',
        ),
    ]
